Rotas PR#1
FaceBike/FaceBike-API pull request #1
Opened 2021-11-08 20:18 UTC by giomioto

rotas cadastro
usuario
todos usuarios
alterar usuario
deletar usuario

2021-11-09 16:33 UTC, JulianoCCMoreira commented on Facebike - API/Entity/userinfo.cs
> +    public class userinfo
Mudar nome da classe para **User**, pois ele se refere a um usuário, e esse usuário é uma entidade que possui já suas propriedades, ou seja, suas _infos_

2021-11-09 16:42 UTC, JulianoCCMoreira requested changes

2021-11-09 16:42 UTC, JulianoCCMoreira commented on Facebike - API/Entity/userinfo.cs
> +        public string senha { get; set; }
Criar métodos construtores das propriedades.

2021-11-09 16:42 UTC, JulianoCCMoreira commented on Facebike - API/Entity/userinfo.cs
> +        public int id { get; set; }
Essas informações foram as alinhadas com o Gustavo Kopp?

2021-11-09 16:42 UTC, JulianoCCMoreira commented on Facebike - API/Entity/userinfo.cs
> +    public class userinfo
Mudar nome da classe para **User**, pois ele se refere a um usuário, e esse usuário é uma entidade que possui já suas propriedades, ou seja, suas _infos_.

2021-11-16 21:59 UTC, JulianoCCMoreira commented on Facebike - API/Controllers/UserController.cs
> +        public ActionResult cadastrar([FromBody] UserDTO user)
Implementar métodos Try/Catch para tratar erros ou excessões.

2021-11-16 21:59 UTC, JulianoCCMoreira commented on Facebike - API/Controllers/UserController.cs
> +        public ActionResult listar()
Implementar métodos Try/Catch para tratar erros ou excessões.

2021-11-16 21:59 UTC, JulianoCCMoreira commented on Facebike - API/Controllers/UserController.cs
> +        public ActionResult filtrar(int code)
Implementar métodos Try/Catch para tratar erros ou excessões.

2021-11-16 21:59 UTC, JulianoCCMoreira commented on Facebike - API/Controllers/UserController.cs
> +        public ActionResult editar([FromBody] UserDTO newUser, int code)
Implementar métodos Try/Catch para tratar erros ou excessões.

2021-11-16 21:59 UTC, JulianoCCMoreira commented on Facebike - API/Controllers/UserController.cs
> +        public ActionResult remover(int code)
Implementar métodos Try/Catch para tratar erros ou excessões.

2021-11-16 22:07 UTC, JulianoCCMoreira requested changes

2021-11-16 22:07 UTC, JulianoCCMoreira commented on Facebike - API/DTO/UserDTO.cs
> +        public int ID { get; private set; }
Fazer com que métodos sejam _"Required"_, para quer assim não sejam nulos.
Para isso, deve fazer o alinhamento com **Gustavo Kopp** para ver quais destes atributos são necessários estarem preenchidos e quais o usuário pode deixar em branco. Caso todos sejam necessários fazer todos _"Required"_. Se não deixar _"Required"_ apenas os que são necessários.

2021-11-18 12:38 UTC, JulianoCCMoreira approved these changes

2021-11-22 14:09 UTC, EduardoFariaKruger approved these changes

2021-11-22 15:43 UTC, alisoonvinicius approved these changes

2021-11-22 15:44 UTC, merged